
Spring:
  servlet:
    avatar-path: ./src/main/resources/static/images/avatar
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  verifiycode: 123456789
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true  # 日志打印SQL语句
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true  # 高亮SQL语句
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  security:
    jwt:
      key: "nihaonihaonihaoa"
      expire: 72
  rabbitmq:
    addresses: 127.0.0.1
    username: admin
    password: admin
  mail:
    host: smtp.163.com
    username: maifuqla@163.com
    password: HMPAKKZFCQTCHESF
    nickname: 博启小分队

simbot:
  # bot 注册完成后自动启动
  auto-start-bots: true
  # bot资源文件的扫描路径
  bot-configuration-resources:
    - 'classpath:simbot-bots/*.bot*'